---
game: quake2
engine: idtech2
encoding: latin1
active: true
version: 34 # Vanilla

server:
  ping:
    recv: "\xff\xff\xff\xffping"
    resp: "\xff\xff\xff\xffack"
  heartbeat:
    recv: "\xff\xff\xff\xffheartbeat"
    resp: "\xff\xff\xff\xffack"
  shutdown:
    recv: "\xff\xff\xff\xffshutdown"
  
client:
  query:
    recv: "query"
    resp: "\xff\xff\xff\xffservers"

misc:
  server_query: !!binary c3RhdHVzIDIzCg==
  server_print: !!binary cHJpbnQ=
