---
# Source: QW/client/protocol.h
game: quakeworld
engine: idtech1
encoding: latin1
active: false
version: 28

server:
  ping:                           # A2A_PING
    recv: "k"
    resp: "l"
  heartbeat:                      # S2M_HEARTBEAT
    recv: "a"
    resp: "l"
  shutdown:                       # S2M_SHUTDOWN
    recv: "C"
  
client:
  query:
    recv: "c"
    resp: "d"
