---
game: quake2
engine: idtech2
encoding: latin1
active: true

server:
  ping:
    recv: !!binary /////3Bpbmc=
    resp: !!binary /////2Fjaw==
  heartbeat:
    recv: !!binary /////2hlYXJ0YmVhdA==
    resp: !!binary /////2Fjaw==
  shutdown:
    recv: !!binary /////3NodXRkb3du
  
client:
  query:
    recv: !!binary cXVlcnk=
    resp: !!binary /////3NlcnZlcnM=

misc:
  server_query: !!binary c3RhdHVzIDIzCg==
  server_print: !!binary cHJpbnQ=
