---
game: quakeworld
engine: idtech1
encoding: latin1
active: false
version: 28

server:
  ping:                           # A2A_PING
    recv: "k\n"
    resp: "l\n"
  heartbeat:                      # S2M_HEARTBEAT
    recv: "a\n" 
    resp: !!binary /////2Fjaw==
  shutdown:                       # S2M_SHUTDOWN
    recv: "C\n"
  
client:
  query:
    recv: !!binary cXVlcnk=
    resp: !!binary /////3NlcnZlcnM=

misc:
  server_query: !!binary c3RhdHVzIDIzCg==
  server_print: !!binary cHJpbnQ=
