version: "3.7"

services:
  master:
    image: masterserver:latest
    ports:
    - target: 27900
      published: 27900
      protocol: udp
      mode: host
    depends_on:
    - dynamodb
    environment:
    - STAGE=TESTING
    - AWS_ACCESS_KEY_ID=0
    - AWS_SECRET_ACCESS_KEY=1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080"]
      interval: 1s
      timeout: 10s
      retries: 3
      start_period: 10s

  dynamodb:
    image: amazon/dynamodb-local
    ulimits:
      nofile:
        soft: "122880"
        hard: "122880"
