version: '3.3'

services:
  master:
    image: masterserver:latest
    ports:
    - target: 27900
      published: 27900
      protocol: udp
      mode: host
    depends_on:
    - redis
    - dynamodb
    environment:
    - STAGE=TESTING

  redis:
    image: redis:alpine

  dynamodb:
    image: amazon/dynamodb-local
    ports:
    - "8000:8000"
    ulimits:
      nofile:
        soft: "122880"
        hard: "122880"
