version: '3.3'

services:
  master:
    image: masterserver:latest
    ports:
    - target: 27900
      published: 27900
      protocol: udp
      mode: host
    depends_on:
    - redis
    - dynamodb
    environment:
    - STAGE=TESTING
    - AWS_ACCESS_KEY_ID=0
    - AWS_SECRET_ACCESS_KEY=1

  redis:
    image: redis:alpine

  dynamodb:
    image: amazon/dynamodb-local
    ulimits:
      nofile:
        soft: "122880"
        hard: "122880"
